/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  __markAsModule(target);
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && key !== "default")
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toModule = (module2) => {
  return __reExport(__markAsModule(__defProp(module2 != null ? __create(__getProtoOf(module2)) : {}, "default", module2 && module2.__esModule && "default" in module2 ? { get: () => module2.default, enumerable: true } : { value: module2, enumerable: true })), module2);
};

// main.ts
__export(exports, {
  default: () => FilePrefixPlugin
});
var import_obsidian = __toModule(require("obsidian"));
var FilePrefixPlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.registerEvent(this.app.workspace.on("file-menu", (menu, file) => {
      if (file instanceof import_obsidian.TFile) {
        menu.addItem((item) => {
          item.setTitle("Prefix with creation date").setIcon("calendar").onClick(async () => {
            await this.prefixFile(file);
          });
        });
      }
    }));
    this.addCommand({
      id: "prefix-file",
      name: "Prefix current file with creation date",
      callback: async () => {
        const file = this.app.workspace.getActiveFile();
        if (file) {
          await this.prefixFile(file);
        } else {
          new import_obsidian.Notice("No active file");
        }
      }
    });
  }
  async prefixFile(file) {
    try {
      const stats = await this.app.vault.adapter.stat(file.path);
      if (!stats) {
        new import_obsidian.Notice("Could not get file stats");
        return;
      }
      const date = new Date(stats.ctime);
      const prefix = date.getFullYear().toString() + (date.getMonth() + 1).toString().padStart(2, "0") + date.getDate().toString().padStart(2, "0") + date.getHours().toString().padStart(2, "0") + date.getMinutes().toString().padStart(2, "0");
      const extension = file.extension;
      const basename = file.basename;
      const newFilename = `${prefix} ${basename}.${extension}`;
      const currentDir = file.path.substring(0, file.path.lastIndexOf("/"));
      const newPath = (0, import_obsidian.normalizePath)(`${currentDir}/${newFilename}`);
      if (await this.app.vault.adapter.exists(newPath)) {
        new import_obsidian.Notice("A file with this prefix already exists");
        return;
      }
      await this.app.fileManager.renameFile(file, newPath);
      new import_obsidian.Notice("File prefixed successfully");
    } catch (error) {
      console.error("Error prefixing file:", error);
      new import_obsidian.Notice("Error prefixing file");
    }
  }
};
