name: Release Obsidian Plugin

on:
  push:
    tags:
      - "*" # Triggers on any tag push

env:
  PLUGIN_NAME: file-prefix # my pugin ID

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Build plugin
        run: npm run build

      - name: Prepare release assets
        run: |
          mkdir $PLUGIN_NAME
          cp main.js manifest.json $PLUGIN_NAME
          zip -r $PLUGIN_NAME.zip $PLUGIN_NAME

      - name: Create Github Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.PLUGIN_NAME }}.zip
          asset_name: ${{ env.PLUGIN_NAME }}.zip
          asset_content_type: application/zip
